# Generated by Django 5.2.7 on 2025-10-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='conf_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('authors', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('pdf_file', models.FileField(upload_to='articles/')),
                ('pub_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.conference')),
            ],
        ),
    ]
